language: python

python:
    - "3.4"
    
services:
  - postgresql

install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database test_db;' -U postgres
  - sed -i 's/название базы данных/test_db/; s/адрес БД/localhost/; s/пользователь для работы с БД/postgres/; s/пароль пользователя//' setup.py

script:
    - python setup.py
    - python setup_db.py
    - python -m unittest discover tests

