#!/bin/sh

printf "[%s]\n"                      "DEFAULT" > config.ini

printf "DB_NAME=%s\n"                "$1" >> config.ini
printf "DB_USER=%s\n"                "$2" >> config.ini
printf "DB_PASSWORD=%s\n"            "$3" >> config.ini
printf "DB_HOST=%s\n"                "$4" >> config.ini

printf "WEBHOOK_HOST=%s\n"           "" >> config.ini
printf "WEBHOOK_PORT=%s\n"           "" >> config.ini

printf "TOKEN=%s\n"                  "$5" >> config.ini

printf "WEEK_TYPE=%u\n"              "$6" >> config.ini
printf "STATISTIC_TOKEN=%s\n"        "$7" >> config.ini

printf "LOG_DIR_PATH=%s\n"           "/bot/log/" >> config.ini

cp /usr/share/zoneinfo/${10} /etc/localtime && echo ${8} > /etc/timezone

gunicorn UniversityScheduleBot:app --workers 4 -b  unix:/bot/socket/bot.sock