#!/bin/sh

printf "[%s]\n"                      "DEFAULT" > config.cfg

printf "DB_NAME=%s\n"                "$1" >> config.cfg
printf "DB_USER=%s\n"                "$2" >> config.cfg
printf "DB_PASSWORD=%s\n"            "$3" >> config.cfg
printf "DB_HOST=%s\n"                "$4" >> config.cfg

printf "TOKEN=%s\n"                  "$5" >> config.cfg

printf "WEEK_TYPE=%u\n"              "$6" >> config.cfg
printf "STATISTIC_TOKEN=%s\n"        "$7" >> config.cfg

printf "LOG_DIR_PATH=%s\n"           "/bot/log/" >> config.cfg

cp /usr/share/zoneinfo/${10} /etc/localtime && echo ${8} > /etc/timezone

gunicorn UniversityScheduleBot:app --workers 4 -b  unix:/bot/socket/bot.sock